# Generated by Django 4.0.6 on 2022-07-15 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('nempresa', models.CharField(max_length=60, unique=True, verbose_name='Nombre de la empresa')),
                ('imgref', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Imagen de Referencia')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('ubicacion', models.CharField(max_length=60, unique=True, verbose_name='Ubicacion del Expedientes')),
                ('imgref', models.ImageField(blank=True, null=True, upload_to='empresa/estante', verbose_name='Imagen de Referencia')),
            ],
            options={
                'verbose_name': 'Estante',
                'verbose_name_plural': 'Estantes',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('noficina', models.CharField(max_length=60, unique=True, verbose_name='Nombre de la Oficina')),
                ('imgref', models.ImageField(blank=True, null=True, upload_to='empresa/oficina', verbose_name='Imagen de Referencia')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_at', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('status', models.CharField(choices=[('A', 'ACTIVO'), ('E', 'EGRESO'), ('J', 'JUBILADO')], default='A', max_length=1, verbose_name='Estatus del Empleado')),
                ('genero', models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO'), ('O', 'OTROS')], default='O', max_length=1, verbose_name='Genero')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('primerNombre', models.CharField(max_length=60, verbose_name='1er Nombre')),
                ('primerApellido', models.CharField(max_length=60, verbose_name='1er Apellido')),
                ('segundoNombre', models.CharField(max_length=60, verbose_name='2do Nombre')),
                ('segundoApellido', models.CharField(max_length=60, verbose_name='2do Apellido')),
                ('fecha_ingreso', models.DateField(verbose_name='F. de Ingreso')),
                ('fecha_egreso', models.DateField(null=True, verbose_name='F. de Egreso')),
                ('observacion', models.TextField(max_length=255, verbose_name='Observaciones')),
                ('doc', models.FileField(blank=True, null=True, upload_to='empresa/doc')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor.empresa')),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor.estante')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor.oficina')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
    ]
